{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 ---\
- name: installing and launching metricbeat\
  hosts: webservers\
  become: yes\
  tasks:\
\
\
  - name: Download metricbeat .deb file\
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb\
\
\
  - name: remove  metricbeat .deb\
    command: dpkg -P metricbeat\
\
  - name: Install 7.4.0\
    command: dpkg -i metricbeat-7.4.0-amd64.deb\
\
  - name: Drop in metricbeat.yml\
    copy:\
      src: /etc/ansible/files/metricbeat-config.yml\
      dest: /etc/metricbeat/metricbeat.yml\
\
\
  - name: enable and configure system module\
    command: metricbeat modules enable docker\
\
\
  - name: Setup metricbeat\
    command: metricbeat setup\
\
\
  - name: Start metricbeat service\
    command: service metricbeat start}